app/routes/faq.tsx

fix cms typecheck on faqs
default to any for now since the cms definition is a little in flux
- etc

Fix FAQs Typecheck

---

app/components/application/AppRequestsRateCard/AppRequestsRateCard.tsx
app/components/shared/CardList/styles.css

This pull request fixes https://pokt.height.app/T-14341

T-14341 Remove icon when value === 0%

---

app/components/application/AppUsageCurrentCard/AppUsageCurrentCard.tsx
app/context/TranslateContext.tsx
app/locales/en.tsx
app/locales/fr.tsx
app/routes/dashboard/apps/$appId/index.tsx

add average relays metric

---

app/components/application/BannerCard/BannerCard.tsx
app/context/TranslateContext.tsx
app/locales/en.tsx
app/locales/fr.tsx
app/views/dashboard/apps/appId/layout/appIdLayoutView.tsx

This pull request adds https://pokt.height.app/team-frontend/T-14353.
No new dependencies were added.

T-14353 New App Provisioning Message Banner

---

app/routes/dashboard/apps/$appId/index.tsx

BE team mentioned that rate limiting only happens for successful relays. And this daily usage card was confusing cause it included errors.
- etc

only show success for daily usage

---

app/views/dashboard/apps/appId/layout/appIdLayoutView.tsx
app/views/dashboard/apps/appId/security/securityView.tsx

Pushing to main from stage branch
Handful of small bug fixes
- etc

Stage -> main

---

app/routes/faq.tsx

- add sort so question order remains consistent even if they are updated.
- update CMS_API_URL: https://pocket-network.directus.app/graphql
- CMS_API_TOKEN: remains the same
- etc

Update directus to new paid project

---

app/views/dashboard/apps/appId/layout/appIdLayoutView.tsx
app/views/dashboard/apps/appId/security/securityView.tsx

- merging the directus sort file.
- the other files already exist in stage and main. after some googling it looks like this has to do with squashing and merging commits. So i turned that off.
- https://stackoverflow.com/questions/16306012/github-pull-request-showing-commits-that-are-already-in-target-branch

Directus stage => main

---

app/views/dashboard/apps/appId/security/securityView.tsx

Fixes security settings page due to some API changes.
- etc

Update production to mirror some small API changes

---

app/context/TranslateContext.tsx
app/locales/en.tsx
app/locales/fr.tsx
app/models/portal/queries.graphqls
app/views/dashboard/apps/appId/layout/appIdLayoutView.tsx
app/views/dashboard/apps/appId/security/securityView.tsx

This removes the banner card that users would get immediately after creating an app.  The banner was used while we had a few troubles with loadbalancers not always being parallel and having the exact same data.  That has since been fixed, so this card is no longer necessary.
- etc

fix: remove 5-minute banner card

---

app/root.tsx

Adds "Support" link to navigation
- etc

fix: add support to main navigation

---

.husky/pre-commit
.husky/pre-push
app/components/application/FeedbackCard/FeedbackCard.test.tsx
app/components/application/NetworkPoktScanLatestBlockCard/NetworkPoktScanLatestBlockCard.test.tsx
app/components/application/NetworkPoktScanLatestBlockCard/NetworkPoktScanLatestBlockCard.tsx
app/components/application/NetworkRelayPerformanceCard/NetworkRelayPerformanceCard.test.tsx
app/components/application/NetworkRelayPerformanceCard/NetworkRelayPerformanceCard.tsx
app/components/application/NetworkSuccessRateCard/NetworkSuccessRateCard.test.tsx
app/components/application/NetworkSummaryCard/NetworkSummaryCard.test.tsx
app/models/poktscan/poktscan.data.ts
app/models/relaymeter/relaymeter.data.ts
app/root.tsx
app/routes/index.tsx
app/routes/network.tsx
app/views/network/networkView.test.tsx
app/views/network/networkView.tsx
app/views/network/styles.css
package.json

> Create Network View file
> Add unit tests to view page and components
- etc

Network view

---

app/models/portal/mutations.graphqls
app/models/portal/queries.graphqls
app/routes/api/stripe/subscription.tsx
app/routes/api/updatePlan.tsx
app/routes/dashboard/apps/$appId.tsx
app/routes/dashboard/create.tsx

This pull request replaces the `updateEndpoint` mutation with `adminUpdatePayPlanType`; also, this enforces all of the Update Plan calls to use the `updatePlan` api call or internal function if you're calling it on the server side.
No new dependencies were added.
- Hardware: **Macbook Pro M1 Pro**
- OS: **macOS 13.0.1**
- Node version: **v16.18**
- PNPM version: **7.16**
No required.

Add adminUpdatePayPlanType mutation

---

app/locales/en.tsx
app/locales/fr.tsx

This pull request updates the number of nodes on the portal landing page from 47K+ to 20K+
No required

T-15929 Update Number of Nodes on Portal Landing Page

---

app/routes/admin/__paths.tsx
app/routes/admin/__paths/customPayPlan.tsx
app/routes/admin/__paths/featureflags.tsx
app/routes/api/updatePlan.tsx
app/styles/admin.css
app/utils/session.server.ts
app/utils/utils.ts

> add custom plan page to admin
> update admin pages to only show for user role in JWT
> add styling to admin
> update plan type utils to handle enterprise
> update "updatePlan" api to handle limit
- etc

 Add Custom Plan Page To Admin

---

app/locales/en.tsx
app/locales/fr.tsx
app/models/portal/mutations.graphqls
app/models/portal/queries.graphqls
app/routes/api/stripe/subscription.tsx
app/routes/api/updatePlan.tsx
app/routes/dashboard/apps/$appId.tsx
app/routes/dashboard/create.tsx

stage to prod

---

app/routes/dashboard/apps.tsx
app/routes/dashboard/create.tsx
app/utils/session.server.ts
app/utils/utils.ts

> protect create page from people who shouldnt be able to create an app. 
> enable users with enterprise permission to create unlimited apps.
- etc

Enable Enterprise Role To Create Unlimited Apps

---

app/routes/dashboard/create.tsx

handle users with no apps

---

catalog-info.yaml
docs/code.md
docs/index.md
docs/infra.md
docs/monitoring.md
docs/quality.md

backstage documentation

---

app/root.tsx
app/routes/dashboard.tsx
app/routes/index.tsx
app/routes/network.tsx
app/utils/analytics.ts
cypress/e2e/landing.test.ts
cypress/e2e/network.test.ts

move analytics init to root. track page views on landing and network page

Marketing Analytics Update

---

app/routes/dashboard/profile.tsx

> A short description of the changes included in your pull request.
> Please do your best to complete all the sections of the template.
> When in doubt, ask for help.
- etc

fix _json error by adding loader

---

app/components/shared/Table/Table.tsx
app/context/TranslateContext.tsx
app/locales/en.tsx
app/locales/fr.tsx

Change the available networks search placeholder to "Search by Network, ID or Status" instead of "Search Available Networks", to make it more clear for the users what they are able to search by.
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] My changes generate no new warnings
- [ x ] New and existing unit tests pass locally with my changes
- [ x ] I have checked my code and corrected any misspellings
- Hardware: Macbook Air
- OS: macOS 12.4
- Node version: 16.18.0
- PNPM version: 7.22.0
video, screenshots, …

Change available networks search placeholder

---

app/models/relaymeter/relaymeter.server.ts
cypress.config.ts

- Added new env variable: "RELAY_METER_API_TOKEN"

feat: Add relay meter token

---

app/components/shared/Modal/styles.css
app/components/shared/NotificationMessage/NotificationMessage.test.tsx
app/components/shared/NotificationMessage/NotificationMessage.tsx
app/components/shared/Text/Text.tsx
app/components/shared/TextInput/styles.css
app/models/portal/mutations.graphqls
app/models/portal/portal.data.ts
app/models/portal/queries.graphqls
app/routes/dashboard/apps/$appId/team.tsx
app/views/dashboard/apps/appId/security/securityView.tsx
app/views/dashboard/apps/appId/team/styles.css
app/views/dashboard/apps/appId/team/teamView.tsx
app/views/dashboard/apps/index/appsView.tsx
package.json
pnpm-lock.yaml

Team access management

---

app/routes/dashboard/apps/$appId/team.tsx
app/views/dashboard/apps/appId/team/teamView.tsx

- Force emails to be lowercase

Fix invite case sensitive

---

app/components/shared/Remark/Remark.tsx
app/components/shared/Remark/styles.css

- update image style to only take up 100% width
- fix directus permissions so public users could see images in the public folder

handle markdown image styling

---

app/routes/dashboard/apps/$appId/team.tsx
app/views/dashboard/apps/appId/team/styles.css
app/views/dashboard/apps/appId/team/teamView.tsx
app/views/dashboard/apps/index/appsView.tsx

This PR will add the role change error message, fix the modal alignment, and fix text misspellings.

fix: prod errors/styles/misspellings

---

app/models/cms/sdk.ts
app/views/dashboard/apps/appId/security/securityView.tsx
cypress/e2e/landing.test.ts

- Improves select component styling
- Fixes issue with landing e2e test

Improvements

---

app/components/application/AppRadioCards/styles.css
app/components/application/ChainWithImage/styles.css
app/components/shared/Header/Header.tsx
app/components/shared/Remark/styles.css
app/styles/landing.css
app/styles/root.css
app/views/dashboard/apps/appId/team/teamView.tsx

This PR fixes small UI bugs such as colors and elements

fix: remix upgrade ui details

---

LICENSE
app/components/application/AppEndpointCard/AppEndpointCard.tsx
app/components/application/AppEndpointUrl/AppEndpointUrl.tsx
app/components/application/ChainWithImage/ChainWithImage.tsx
app/components/application/ChainsDropdown/ChainsDropdown.tsx
app/components/shared/Footer/Footer.tsx
app/models/portal/portal.data.ts
app/views/dashboard/apps/appId/security/securityView.tsx
app/views/dashboard/apps/index/appsView.tsx
app/views/network/networkView.tsx

This PR will fix small issues found in the prod env.

fix: prod copywrite, teams table, chains dropdown

---

app/components/shared/MaintenanceNotification/MaintenanceNotification.tsx

update date to 26th

---

app/components/application/AppPlanDetails/AppPlanDetails.tsx
app/components/application/FeedbackCard/FeedbackCard.test.tsx
app/components/application/FeedbackCard/FeedbackCard.tsx
app/components/shared/Card/Card.tsx
app/components/shared/Footer/Footer.tsx
app/components/shared/Icons/IconDiscord.tsx
app/components/shared/Table/Table.tsx
app/context/TranslateContext.tsx
app/locales/en.tsx
app/locales/fr.tsx
app/locales/types/SecurityPageTypes.ts
app/routes/dashboard/apps/$appId/notifications.tsx
app/views/dashboard/apps/appId/security/securityView.tsx
app/views/dashboard/apps/index/appsView.tsx
cypress/e2e/landing.test.ts

- Update discord link
- Wrap table row inside link to add similar effect as Spotify UI
- Added descriptions for each security option
- Change pay as you go button variant to primary
- Removed outdated text in notifications
- Wrapped feedback box inside link and added overlay similar to table row
- App name adjust edit button
- Update relay count graph

UI improvements

---

app/views/dashboard/apps/index/appsView.tsx

- Changing "Teams" to "My Teams" under "Apps" tab

Changing "Teams" to "My Teams"

---

app/routes/dashboard/create.tsx

- Fixes terms of use link styling
- Fixes terms of use link path

Terms of service link

---

app/components/Sidebar/Sidebar.tsx
app/routes/_landing.($lang).docs/components/footer/footer.tsx
app/routes/_landing.($lang).docs/route.tsx

- Refactoring documentation layout to use AppShell for a better UX
------------------------------------------------------------------------------------

Refactoring documentation layout to use AppShell for a better UX

---

app/components/Sidebar/Sidebar.tsx
app/routes/_landing.($lang).docs/route.tsx

- Moved the Search to the content area to be on the same line with the first item in the sidebar.
- Moved the footer to be closer to the content and be within the content area as it shouldn't expand below the sidebar.
- Fixed the sidebar overflowing over the footer.
- Added scroll to the sidebar when there are overflown items.

Fixing Layout issues that appeared after using AppShell

---

app/components/SearchAutoCompleteItem/SearchAutoCompleteItem.test.tsx
app/components/SearchAutoCompleteItem/SearchAutoCompleteItem.tsx
app/routes/_landing.($lang).docs/components/Breadcrumbs/Breadcrumbs.tsx
app/routes/_landing.($lang).docs/components/DocumentationSearch/DocumentationSearch.tsx
app/routes/_landing.($lang).docs/hooks/useDocumentationSearch.tsx
app/routes/_landing.($lang).docs/route.tsx

- Fixed link the search results link, in order to align with other links in the side menu/footer

Redirect to the correct links from the search

---

app/components/LinksGroup/LinksGroup.test.tsx
app/components/LinksGroup/LinksGroup.tsx
app/root.tsx
app/routes/_landing.($lang).docs/components/footer/footer.tsx
test/helpers.tsx

> update test helper to handle our customer mantine theme
- etc

Mantine tests

---

app/components/Table/Table.tsx
app/components/Table/TableBody.tsx
app/components/Table/TableHeader.tsx
app/components/Table/TablePagination.tsx
app/hooks/usePagination.ts
app/root.tsx
app/routes/$/route.tsx
app/routes/dashboard.apps.$appId.team/view.tsx
app/routes/dashboard.apps._index/view.tsx
app/types/table.d.ts

1. Refactor Table component
1.1 Add `TableHeader`, `TableBody`, and `TablePagination` components 
1.2 Add `usePagination` hook
1.3 Add `table.d.ts` types definition
2. Fix `dashboard/apps` container
3. Fix missing `routes/$` action

refactor Table component

---

app/routes/_landing.($lang).docs.$/route.tsx

- Adding title and SEO description to docs

Adding title and SEO description to docs

---

app/routes/_landing.($lang).docs/components/DocumentationSearch/DocumentationSearch.tsx
app/routes/_landing.($lang).docs/hooks/useDocumentationSearch.tsx

- Changes right section to be an absolute element 
- Removes right section styling object because it had no effect on the actual element

Fix docs searchbar mobile styling

---

app/models/cms/queries.graphqls
app/routes/_landing.($lang).docs/hooks/useDocumentationSearch.tsx
app/routes/api.search-docs/route.tsx

- Parent docs are now excluded from search results

Exclude parent docs from search results

---

app/components/Remark/Remark.tsx
app/routes/_landing.($lang).docs/components/DocAside/DocAside.tsx
app/routes/_landing.($lang).docs/components/DocAside/index.ts
app/routes/_landing.($lang).docs/components/footer/footer.tsx
app/routes/_landing.($lang).docs/route.tsx
app/utils/docs.ts
package.json
pnpm-lock.yaml

- Using rehype-slug to attach anchor ids to headers 
- Adding Docs right aside section with sticky position 
- Fixing small styling issues
- Hiding aside and links sidebar for tablet screens

Docs right sidebar 

---

app/components/ChainsDropdown/ChainsDropdown.tsx
app/components/application/AppEndpointCard/AppEndpointCard.test.tsx
app/components/application/AppEndpointCard/AppEndpointCard.tsx
app/components/application/UsageChartCard/UsageChartCard.tsx
app/models/relaymeter/relaymeter.data.ts
app/routes/_landing.network/route.tsx
app/routes/_landing.network/view.test.tsx
app/routes/_landing.network/view.tsx
app/routes/dashboard.apps.$appId._index/route.tsx
app/routes/dashboard.apps.$appId.notifications/components/NotificationsWeeklyBandwidthUsageCard/NotificationsWeeklyBandwidthUsageCard.tsx
app/routes/dashboard.apps.$appId.security/view.tsx
app/routes/dashboard.apps.$appId/route.tsx
app/routes/dashboard.apps._index/route.tsx
app/routes/dashboard.apps._index/view.test.tsx
app/routes/dashboard.apps._index/view.tsx

* Add ChainsDropdown Checkbox item component (App Overview page, Security page)
* Add relay count graph filter (Network page, Apps Overview page, App Overview page)

add Chains Dropdown Checkbox and relay count graph filters

---

app/locales/en.tsx
app/locales/fr.tsx

Removing FAQs link from legacy banner

refactor: Removing FAQs link from legacy banner

---

app/routes/dashboard.apps.$appId/route.tsx
app/routes/dashboard.apps.$appId/view.tsx

udpate api path to update plan

---

app/routes/dashboard.apps.$appId/components/StopRemoveApp/StopRemoveApp.tsx

-  Fixing app delete button not working

App delete button not working

---

app/routes/api.auth.auth0/route.tsx

- Forget user session after logout

Forget user session after logout

---

app/routes/admin.users.pay-plan/route.tsx
app/routes/api.admin.update-plan/route.tsx
app/routes/api.stripe.subscription/route.tsx

- Fixing admin portal API to update plan type

Update plan type via admin portal fix

---

app/components/MaintenanceNotification/MaintenanceNotification.tsx

- Update maintenance notification message

Update maintenance notification message

---

app/routes/dashboard.apps._index/view.tsx

Update accept invite form to include portalUserID

Fix Accept Invite

---

app/routes/dashboard.apps._index/route.tsx
app/routes/dashboard.apps._index/view.tsx

update accept invite form to include portalUserID

PROD: PortalUserID

---

app/routes/dashboard.apps.$appId/view.tsx

update path to update-plan

---

app/routes/dashboard.apps.$appId._index/route.tsx

Flip session limit logic

---

app/components/TitledCard/TitledCard.tsx
app/components/TitledCard/index.ts
app/root/hooks/useRoot.tsx
app/root/portalTheme.ts
app/routes/dashboard._index/route.tsx
cypress/e2e/dashboard.test.ts
package.json
pnpm-lock.yaml

- add account overview page
- add card component and utilize it within the overview
- add recharts and add mock graphs for now
- a little bit of theme updates

Initial: add account overview page

---

app/routes/dashboard.apps.$appId.team/route.tsx
app/routes/dashboard.apps.$appId.team/view.tsx
app/routes/dashboard.apps._index/view.tsx

- Fix team member actions (update role, delete, and leave)

Fix team member actions (update role, delete, and leave)

---

app/routes/dashboard.apps.$appId/route.tsx
app/routes/dashboard.apps.$appId/view.test.tsx
app/routes/dashboard.apps.$appId/view.tsx

- Fix: pay plan changes to free when a non-owner team member views the app

App pay plan fix

---

app/routes/dashboard.apps.$appId.team/view.tsx

- Disable app ownership transfer for now

Disable app ownership transfer for now

---

app/routes/api.stripe.checkout-session/route.tsx

allow promo codes in the stripe checkout session

Stripe Promo Codes

---

app/routes/api.auth.auth0/route.tsx

Logout Redirect Error

---

app/components/AccountPlan/AccountPlan.tsx
app/components/AppHeader/AppHeader.tsx
app/components/Sidebar/Sidebar.tsx
app/root.tsx
app/root/portalTheme.ts

- Use system fonts instead of Manrope
- Update icons to Lucide icons
- More theme alignments and color fixes
- Account plans copy update

System fonts + theme alignments

---

app/root/components/RootProviders/RootProviders.tsx
app/root/portalTheme.ts
app/routes/account.$accountId.$appId/hooks/useSubscriptionSync.tsx
package.json
pnpm-lock.yaml

- Add notifications system and show notifications after app subscription

Notifications system

---

app/components/Chain/Chain.tsx
app/routes/account.$accountId.$appId._index/components/AppEndpointsTable/AppEndpointsTable.tsx
app/routes/account.$accountId.$appId._index/components/FavoriteChain/FavoriteChain.tsx
app/routes/account.$accountId.$appId._index/components/FavoriteChain/index.ts
app/routes/account.$accountId.$appId._index/route.tsx
app/routes/account_.$accountId.$appId.update/route.tsx
vitest.config.ts

add favorite chain functionality to application endpoints

Favorite Chains

---

app/routes/account_.$accountId.create/route.tsx
app/routes/api.stripe.checkout-session/route.tsx
vitest.config.ts

fix stripe api checkout session redirect

Stripe Auto Scale Redirect Fix

---

app/components/Identicon/Identicon.tsx
app/components/OrganizationDrawer/OrganizationDrawer.tsx
app/components/OrganizationSelect/OrganizationSelect.tsx
app/utils/identicons.ts
package.json
pnpm-lock.yaml

add identicon for account

---

app/utils/mail.server.ts

@zaynepokt what return email should we be using here?

STAGE: update mailgun to grove

---

app/components/AppHeader/AppHeader.tsx
app/components/OrganizationDrawer/OrganizationDrawer.tsx
app/components/RootAppShell/RootAppShell.tsx
app/models/portal.server.ts
app/models/portal/mutations.graphqls
app/models/portal/portal.data.ts
app/models/portal/queries.graphqls
app/root/hooks/useRoot.tsx
app/routes/account.$accountId.$appId.plan/route.tsx
app/routes/account.$accountId.$appId.team/route.tsx
app/routes/account.$accountId.$appId.team/view.tsx
app/routes/account.$accountId.$appId/route.tsx
app/routes/account.$accountId.apps._index/route.tsx
app/routes/account.$accountId.apps._index/view.tsx
app/routes/account.$accountId.apps/route.tsx
app/routes/account.$accountId/route.tsx
app/routes/account_.$accountId.create/route.tsx
app/routes/admin/route.tsx
app/routes/api.stripe.checkout-session/route.tsx
app/routes/api.stripe.portal-session/route.tsx
app/routes/api.stripe.subscription/route.tsx
app/routes/api.user/route.tsx
app/routes/user.profile/route.tsx
app/routes/user.profile/utils/actionPassword.ts
app/routes/user.profile/utils/actionUser.ts
app/routes/user.profile/view.test.tsx
app/routes/user.profile/view.tsx
app/routes/user/route.tsx
app/utils/auth.server.ts
app/utils/user.server.ts

- handle user profile actions
- update auth.server user structure and pass our definition of a user instead of auth0s
- update all instances where we used user.profile

Profile Actions

---

app/utils/user.server.ts

logout user if they dont have the user value in the session cookie.

Session Update

---

app/routes/account.$accountId/route.tsx

- filter out deleted apps from the shown list in the sidebar

Filter Deleted apps

---

app/routes/account_.$accountId.create/components/AppForm/AppForm.tsx

- ensure button is clickable when updating an app without having to modify the name

setName default to app name so user can click update button

---

app/routes/account.$accountId.$appId._index/components/FavoriteChain/FavoriteChain.tsx
app/routes/account.$accountId.$appId._index/route.tsx
app/routes/user.profile/view.tsx
app/utils/loader.ts

- handle favorite endpoint notifications for success and error
- improve favorite endpoint by showing user the action right away instead of waiting for action to finish
- handle notification for profile errors

Notifications

---

app/components/OrganizationDrawer/OrganizationDrawer.tsx
app/components/OrganizationSelect/OrganizationSelect.tsx
app/models/portal/mutations.graphqls
app/models/portal/queries.graphqls
app/routes/_index/route.tsx
app/routes/account.$accountId.$appId._index/components/FavoriteChain/FavoriteChain.tsx
app/routes/account.$accountId.$appId.team/components/InviteMemberForm/InviteMemberFrom.tsx
app/routes/account.$accountId.$appId.team/components/TeamMemberAction/TeamMemberAction.tsx
app/routes/account.$accountId.$appId.team/components/TeamMembersTable/TeamMembersTable.tsx
app/routes/account.$accountId.$appId.team/hooks/useTeamModals.tsx
app/routes/account.$accountId.$appId.team/route.tsx
app/routes/account.$accountId.$appId.team/view.tsx
app/routes/account.$accountId/route.tsx
app/routes/account._index/route.tsx
app/routes/account/route.tsx
app/routes/user.invited-apps/route.tsx
app/utils/auth.server.ts
app/utils/mail.server.ts
app/utils/user.server.ts

- update team actions to v2
- handle invite, delete, update, resend
- make role actions more clear
- add mutations
- update default account fallback logic
- fix key error in console
- fix favorite endpoint

Team actions

---

app/components/RootAppShell/RootAppShell.tsx
app/components/Sidebar/Sidebar.tsx
app/root.tsx

- Only allow owner users to create apps within an org

Only allow owner users to create apps within an org

---

app/components/Sidebar/Sidebar.tsx
app/routes/account.$accountId.$appId.keys/view.tsx
app/routes/account.$accountId.$appId.security/components/ApprovedChains/ApprovedChains.tsx
app/routes/account.$accountId.$appId.security/components/PrivateSecretKey/PrivateSecretKey.tsx
app/routes/account.$accountId.$appId/components/ApplicationHeader/ApplicationHeader.tsx
app/routes/user.profile/view.tsx

allow app id to be copied. update copy changes

Copy Changes

---

app/routes/user.invited-apps/route.tsx

call api twice to get both accepted and pending apps

Fix Invited Apps

---

app/root.tsx
app/root/components/Document/Document.tsx
app/root/portalTheme.ts

- move rootProviders inside html and head tags
- move global styles to theme

fix page title

---

app/routes/api.stripe.webhook/route.tsx

update webhook to post on session complete instead of subscription create since that doesnt have the metadata yet.

Stripe Webhook

---

app/routes/account.$accountId.$appId/components/DeleteApplication/DeleteApplication.tsx
app/routes/account.$accountId.$appId/route.tsx

- ensure action points to the correct route
- redirect to account on success
- redirect to account on "app not found" error in loader

Fix Delete App

---

app/hooks/useActionNotification.tsx
app/routes/account.$accountId.$appId._index/components/AppEndpointsTable/AppEndpointsTable.tsx
app/routes/account.$accountId.$appId.security/view.tsx
app/routes/account.$accountId.$appId.team/hooks/useTeamModals.tsx
app/routes/account.$accountId.$appId/route.tsx
app/routes/account_.$accountId.$appId.update/route.tsx
app/routes/account_.$accountId.create/route.tsx
app/routes/account_.$accountId.update/route.tsx
app/routes/user.invited-apps/route.tsx
app/routes/user.profile/route.tsx

-  Add icons to notifications and move the logic to useActionNotification hook

New UI: Notifications

---

app/routes/api.stripe.webhook/route.tsx

remove application/json header to pass data as a formData

Fix Stipe Webhook 2

---

app/routes/account.$accountId.$appId.notifications/components/AppNotificationsAlert/AppNotificationsAlert.tsx

- fix notifications notifications. 
- update ui to have divider like security and endpoints

Fix Notifications Notifications

---

app/components/AccountDrawer/AccountDrawer.tsx
app/components/Sidebar/Sidebar.tsx
app/routes/account.$accountId.$appId._index/components/AppEndpointsTable/AppEndpointsTable.tsx
app/utils/utils.ts
cypress/e2e/landing.test.ts

- add single constant for docs path

Fix Docs Path

---

app/routes/account.$accountId._index/components/AccountAppsOverview/AccountAppsOverview.tsx
app/routes/account.$accountId._index/view.tsx

- Update copy from org to account

Copy update

---

app/routes/api.stripe.webhook/route.tsx

make path absolute not relative

Stripe Webhook Delete

---

app/routes/account.$accountId._index/view.tsx

- Setting max success rate to 100 instead of "auto"

Success rate domain fix

---

app/components/DataTable/DataTable.tsx
app/models/dwh/openapi.yaml
app/models/dwh/sdk/.openapi-generator/FILES
app/models/dwh/sdk/apis/UserApi.ts
app/routes/account.$accountId.$appId.logs/components/LogsSideDrawer/LogsSideDrawer.tsx
app/routes/account.$accountId.$appId.logs/components/LogsTable/LogsTable.tsx
app/routes/account.$accountId.$appId.logs/route.tsx
app/routes/account.$accountId.$appId.logs/view.tsx
app/routes/account.$accountId.$appId.team/route.tsx
app/routes/account.$accountId.$appId/view.tsx
app/styles/root.css
app/types/table.d.ts

- Update openapi.yaml and logs API
- Add support for table loading overlay & fix hover style applying to all tables
- Implement logs pagination and add seconds to logs time formatting
- Remove logs search and add custom empty state message when end of logs pages is reached

Logs pagination

---

app/routes/account.$accountId.$appId/view.tsx

- Renaming Logs tab -> Error Logs

Renaming Logs tab -> Error Logs

---

app/routes/account_.$accountId.app-limit-exceeded/route.tsx
app/routes/account_.$accountId.create/route.tsx
app/utils/accountUtils.ts
app/utils/planUtils.ts

- Allow Enterprise accounts to create unlimited apps
- Remove user based permissions
- Remove GODMODE accounts logic

Allow Enterprise accounts to create unlimited apps

---

app/components/FluidSelect/FluidSelect.tsx
app/components/FluidSelect/index.ts

- An extended component that represents a select that dynamically resizes depending on its contents
- Allows custom item rendering

FluidSelect component

---

app/components/Sidebar/Sidebar.tsx
app/models/portal/queries.graphqls
app/routes/account.$accountId.sandbox/route.tsx
app/routes/account.$accountId.sandbox/view.tsx

Sandbox standalone feature 🎉

---

app/components/AppHeader/AppHeader.tsx
app/components/RootAppShell/RootAppShell.tsx
app/components/Sidebar/Sidebar.tsx
app/entry.client.tsx
app/root.tsx
app/root/components/Document/Document.tsx
app/routes/user/route.tsx

Using React 18 `hydrateRoot` instead of `hydrate`

Mantine V7 w/ `hydrateRoot`

---

app/components/ChainSandbox/ChainSandbox.tsx
app/components/ChainSandbox/components/ChainSandboxBody/ChainSandboxBody.tsx
app/components/ChainSandbox/components/ChainSandboxInputs/ChainSandboxInputs.tsx
app/components/ChainSandbox/state/chainSandboxContext.tsx
app/components/ChainSandbox/state/stateReducer.ts
app/routes/api.sandbox/route.tsx

Adding `GET` method support to the Sandbox

---

app/routes/api.stripe.checkout-session/route.tsx
app/routes/api.stripe.webhook/route.tsx
app/utils/planUtils.ts

fixing edge cases and troubleshooting the stripe checkout flow

fixing legacy plan issue

---

README.md
app/routes/account_.$accountId.update/components/AccountForm/AccountForm.tsx

fix: relay limit text

---

README.md
app/routes/account_.$accountId.create/components/AccountPlansContainer/AccountPlansContainer.tsx

- Specify `npm version`
- Add pnpm build step
- Add link to where the env is
https://github.com/user-attachments/assets/c38606f5-6f5c-4f26-903a-2aaeec36b86b
https://github.com/user-attachments/assets/05cd10b3-1b5b-48ce-87de-6692dcf29487

README update 

---

README.md
app/routes/account_.$accountId.create/components/AccountPlansContainer/AccountPlansContainer.tsx
app/routes/account_.$accountId.update/components/AccountForm/AccountForm.tsx

https://github.com/user-attachments/assets/1f0c7a87-541d-4ae7-8056-5bd78a3209ed

[Urgent Release] Bug fix for new app creation

---

app/components/CodeEditor/CodeEditor.tsx
vercel.json
vite.config.ts

Quick PR to try and get our Google Search Console Errors solved.

Add HTTP Headers to disallow bot crawling
