pokt-foundation/grove-portal

- app/components/application/AppPlansOverview/AppPlansOverview.tsx
- app/locales/en.tsx
- app/locales/fr.tsx
Fix links going to /dashboard/contact-sales instead of /contact-sales
> fix: contact sales link

- app/models/errormetrics/errormetrics.server.ts
- app/root.tsx
- app/routes/faq.tsx
- app/utils/session.server.test.ts
- package.json
- pnpm-lock.yaml
- test/setup-test-env.ts
- vitest.config.ts
This pull request updates Remix to 1.7.4 cause it was having issues with Mantine; the reason for the problem is that we were using a version of Remix older than Mantine 5, and Mantine 5 SSR was created for the most recent version of Remix.
```
- "@remix-run/node": "^1.7.4",
- "@remix-run/react": "^1.7.4",
- "@remix-run/vercel": "^1.7.4",
- "@pokt-foundation/pocket-blocks": "^2.0.1",
```
Fill in those that apply, and remove the rest.
- Node version: **16.18.0**
- PNPM version: **7.14.1**
No required.
> T-15536 - Fix styling issues between Mantine 5 and Remix

- app/context/TranslateContext.tsx
- app/locales/en.tsx
- app/locales/fr.tsx
- app/routes/api/auth/auth0.tsx
> Auth0 was keeping a user session even after logging out. We have had enough people complain about this.
>  Change: force redirect to auth0 instead of keeping session
> users will now be forced to fully log back in
> force redirect to auth0 instead of keeping session

- .husky/pre-commit
- app/components/application/AppAddressCard/AppAddressCard.test.tsx
- app/components/application/AppAddressCard/AppAddressCard.tsx
- app/components/application/AppKeysCard/AppKeysCard.tsx
- app/components/shared/RevealIcon/RevealIcon.tsx
- app/components/shared/TextInput/TextInput.tsx
- app/locales/en.tsx
- app/locales/fr.tsx
Enable the hide/show function on the user App Address section. The default is hidden and the user can click to show the address of each item on a list of addresses.
Note: Changed pre-commit test command. 
- Hardware: **Macbook Air M1**
- OS: **macOS 12.4**
- Node version: **16.18.0**
- PNPM version: **7.22.0**
> feat: add hidden account addresses

- app/views/dashboard/apps/appId/team/teamView.tsx
new error message:
Ownership transfer failed
The user has already reached the maximum number of applications that can be owned.
> update error message for ownership change

- app/components/shared/Modal/Modal.tsx
- app/components/shared/Modal/styles.css
> fix modal centering

- app/components/shared/TextInput/TextInput.tsx
- app/views/dashboard/apps/index/appsView.tsx
- Fixes text input component styling
- Moves input background from the entire component to only wrap the input
- Adds weight to the label and increases size to 1em (16px)
> fix: textinput styling

- app/views/dashboard/apps/appId/layout/appIdLayoutView.tsx
After making a payment the plan won't upgrade from Free tier to Paid tier. 
This PR fixes the problem by adding a useEffect logic to check every time the user goes to the apps page to upgrade from the Free tier.
> fix: plan not updating if the user has a subscription

- app/routes/_landing.($lang).docs.$/route.tsx
- app/utils/docs.ts
- Fixes docs routing. Basically allows docs to have routes like introduction/what-is-the-portal. This is possible because of splat routes.
- Fixes sidebar links
> feat: use splat route to get nested routing inside docs

- app/hooks/usePagination.ts
- app/routes/_landing.($lang).docs/components/DocumentationSearch/DocumentationSearch.tsx
- app/routes/_landing.($lang).docs/hooks/useDocumentationSearch.tsx
- Added mobile version of docs search bar component. I used media query Mantine component to completely separate concerns with the desktop version
- Added new state "mobileExpanded" which helps control when the mobile version should "expand". It opens when clicked and closes when clicked outside (behaves just like the dropdown).
- Added description to dropdown fields to match expected behavior
- Updated dropdown styles to match designs
https://github.com/pokt-foundation/pocket-portal/assets/26576400/b234d006-d177-4495-9c1c-871f8dfaefff
> Mobile searchbar

- app/routes/dashboard.apps.$appId/view.tsx
- fixing inconsistent update-plan API calls after cancelling a subscription
Fixing this issue: 
https://www.loom.com/share/af6f2b0ac2924417b40a62e36344874e
> Fixing inconsistent update-plan API calls after cancelling a subscription

- app/root.tsx
- app/root/hooks/useRoot.tsx
- app/routes/admin._index/route.tsx
- app/routes/admin.settings.feature-flags/route.tsx
- app/routes/admin.users.pay-plan/route.tsx
- app/routes/admin/route.tsx
- Fix admin portal broken routes and styles
- Set custom pay plan as default landing route
- Added meta info (title) to the routes
> Fix admin portal broken routes and styles

- app/routes/dashboard.apps._index/route.tsx
update relay meter to use the full user id instead of the parsed user id. 
example: `auth0|1232546757` vs `1232546757`
> use full auth0 id and not parsed id

- app/routes/dashboard.apps.$appId/route.tsx
- ensure we get stripe subscription details using owner email and not based on team admin/member email addresses.
> use the owner email to find subscription details

- app/components/Header/Header.tsx
- app/routes/api.auth.auth0/route.tsx
change Link to anchor so that it forces plasmic to load through the server and not client side.
--- 
We are seeing an issue where when the user is logged into the dashboard and tries to return to the homepage, plasmic is not loading correctly.
This is most likely due to the fact that the PlasmicProvider does not live on the dashboard and when trying to load the provider from the client side without it we get this error.
> Dashboard => Homepage Bug

- app/components/AppHeader/AppHeader.tsx
- app/components/DataTable/DataTableBody.tsx
- app/components/OrganizationSelect/OrganizationSelect.tsx
- app/hooks/useModals.tsx
- app/routes/account.$accountId.$appId.team/components/InviteMemberForm/InviteMemberFrom.tsx
- app/routes/account.$accountId.$appId.team/components/TeamMemberAction/TeamMemberAction.tsx
- app/routes/account.$accountId.$appId.team/components/TeamMembersTable/TeamMembersTable.tsx
- app/routes/account.$accountId.$appId.team/hooks/useTeamModals.tsx
- app/routes/account.$accountId.$appId.team/route.tsx
- app/routes/account.$accountId.$appId.team/view.tsx
- app/routes/user.invited-apps/components/InvitedAppAction/InvitedAppAction.tsx
- app/routes/user.invited-apps/components/InvitedAppsTable/InvitedAppsTable.tsx
- Add correct leave action under user profile -> invited apps
- Fix accountId used as undefined due to usage outside of accounts routes
- Close invite member modal upon action completion instead of always closing after one second
> Team actions follow up

- app/routes/account.$accountId.$appId.notifications/components/AppNotificationsAlert/AppNotificationsAlert.tsx
- Fixing Notifications events not updating correctly
> App notifications fix

- app/components/Sparkline/Sparkline.tsx
- app/routes/account.$accountId.$appId.insights/view.tsx
- app/routes/account.$accountId.$appId.logs/route.tsx
- app/routes/account.$accountId.$appId.security/components/ApprovedChainsModal/ApprovedChainsModal.tsx
- app/routes/account.$accountId.$appId.security/components/WhitelistUserAgentsModal/WhitelistUserAgentsModal.tsx
- app/routes/account.$accountId._index/route.tsx
- app/routes/account.$accountId._index/view.tsx
- app/routes/account_.$accountId.create/components/AppForm/AppForm.tsx
- app/styles/root.css
- app/utils/chartUtils.ts
- Fixing appmoji resetting to default when app name or description are updated
- Insights card title html fixes, as nested divs inside p tag caused errors and hydration issues
- Clean up and error logging
- Handle the case when there are no errors but there are relays
> Fixes and clean up

- app/models/portal/queries.graphqls
- app/routes/account.$accountId.$appId.team/components/TeamMemberAction/TeamMemberAction.tsx
- app/routes/account.$accountId.$appId.team/components/TeamMembersTable/TeamMembersTable.tsx
- app/routes/account.$accountId.$appId/route.tsx
- app/routes/account.$accountId/route.tsx
- app/routes/account_.$accountId.$appId.update/route.tsx
- app/routes/user.accounts/components/AccountsTable/AccountsTable.tsx
- app/routes/user.invited-apps/view.tsx
- app/utils/applicationUtils.ts
- app/utils/user.server.ts
- app/utils/user.ts
Update apps and accounts queries and align usage based on the new fields
> New account and apps users structure

- app/components/AccountDrawer/AccountDrawer.tsx
- app/root/hooks/useRoot.tsx
- app/routes/account.$accountId.settings.members/components/TeamMembersTable/TeamMembersTable.tsx
- app/routes/account.$accountId.settings.members/hooks/useTeamModals.tsx
- app/routes/account.$accountId.settings.plan/components/AutoScalePlanLatestInvoiceCard/AutoScalePlanLatestInvoiceCard.tsx
- app/routes/account.$accountId.settings.plan/components/AutoScalePlanOverviewCard/AutoScalePlanOverviewCard.tsx
- app/routes/account.$accountId.settings.plan/components/EnterpriseAccountOverviewCard/EnterpriseAccountOverviewCard.tsx
- app/routes/account.$accountId.settings.plan/route.tsx
- app/routes/user.accounts/components/AccountsTable/AccountsTable.tsx
- app/utils/utils.ts
- Use correct Auto-Scale account last invoice billed relays value
- Metrics API fixes
- Account plan updates and alignments
- Update my profile page link
- Use `capitalizeFirstLetter` where needed
- Initial value of Role dropdown after inviting a user is sometimes incorrect
> Account fixes

- app/utils/auth.server.ts
Removing the extra params from the auth cookie context since its not used and taking up a bunch of space.
> Google Oauth

- app/utils/user.server.ts
handle case where portalUserId doesnt exist and re-login the background.
note: I tested this by setting the portalUserID value to null right before this and it successfully logged me in the background without the user noticing
> Auth: !PortalUserID

- app/components/AccountSelect/AccountSelect.tsx
- app/components/Identicon/Identicon.tsx
- app/components/Sidebar/Sidebar.tsx
- app/components/Sidebar/components/SidebarApps.tsx
- app/components/Sidebar/components/SidebarNavLinks.tsx
- Removing icons from sidenav routes
- Small changes to the identicon size and border radius
- Smaller sidenav width
- Removing Grove logo
> New sidenav

- app/routes/account.$accountId.settings.plan/hooks/useSubscriptionModals.tsx
- app/routes/api.stripe.subscription-delete/route.tsx
- app/routes/api.stripe.webhook/route.tsx
Handle `customer.subscription.deleted` in stripe webhook and fix manual subscription cancellation
> Stripe fixes

- app/components/AccountPlan/AccountPlan.tsx
- app/components/Sidebar/Sidebar.tsx
- app/models/portal/portal.data.ts
- app/routes/account.$accountId.settings.plan/components/FreeAccountPlan/FreeAccountPlan.tsx
- app/routes/account.$accountId.settings.plan/components/FreeAccountPlan/index.ts
- app/routes/account.$accountId.settings.plan/components/FreePlanLimitCard/FreePlanLimitCard.tsx
- app/routes/account.$accountId.settings.plan/components/FreePlanLimitCard/index.ts
- app/routes/account.$accountId.settings.plan/components/UnlimitedAccountOverviewCard/UnlimitedPlanOverviewCard.tsx
- app/routes/account.$accountId.settings.plan/components/UnlimitedAccountOverviewCard/index.ts
- app/routes/account_.$accountId.upgrade/route.tsx
- app/utils/notifications.server.ts
- app/utils/planUtils.ts
- app/utils/updatePlan.server.ts
- pnpm-lock.yaml
Changes all the things wrt to Free / PAYG / Enterprise to Free / Unlimited
> Pricing update

- app/models/stripe/stripe.data.ts
- app/routes/api.stripe.checkout-session/route.tsx
This updates the Stripe checkout session for creating a new subscription on the unlimited plan to set the billing cycle anchor date as 12:00 UTC on the first day of the next month.
> fix: set billing cycle anchor

- app/models/portal/queries.graphqls
- app/routes/account.$accountId.settings._index/view.tsx
- app/routes/account_.$accountId.update/components/AccountForm/AccountForm.tsx
- app/routes/account_.$accountId.update/route.tsx
Adds a section to the Account Settings page to display and update the Monthly User Limit.
Feature added:
https://github.com/user-attachments/assets/5f387dea-bea3-49bc-a1f8-09699e2119bd
> feat: update monthly relay limit UI

- app/utils/chainUtils.ts
Fixes the issue of the Sandbox displaying error for new F-chains by altering the hardcoded chains list to use EVM chain IDs.
> fix: update sandbox to use F-chain EVM chain IDs
